import { CodInfo } from './cod-info.model';
import { HazmatInfo } from './hazmat-info.model';
import { HoldAtLocInfo } from './hold-at-loc-info.model';
import { LtlPkgInfo } from './ltl-pkg-info.model';
import { ReturnShipmentInfo } from './return-shipment-info.model';
import { ShipmentChargesInfo } from './shipment-charges-info.model';
import { UspsPkgInfo } from './usps-pkg-info.model';

export class ShipmentPackagesInfo {
  clientId: number = 0;
  packageNum: number = 0;
  shipmentId: number = 0;
  additionalHandlingFlag: boolean = false;
  additionalHandlingType: string = '';
  additionalLabelCount: string = '';
  weight: number = 0;
  weightUomCode: string = '';
  voidPackageFlag: boolean = false;
  bolnumber: string = '';
  commodityDesc: string = '';
  connDescription: string = '';
  connMsn: string = '';
  customsOptionsType: string = '';
  packageDecValueCurr: string = '';
  description: string = '';
  dimensionId: number = 0;
  dimensionName: string = '';
  dimWeightUom: string = '';
  dimensionWeight: number = 0;
  dryIceFlag: boolean = false;
  dryIceUnits: string = '';
  dryIceWeight: number = 0;
  enhancementTypes: string = '';
  eodFlag: boolean = false;
  expectedDeliveryDate: string = '';
  fedexPriorityAlert: boolean = false;
  fedexPriorityAlertFlag: boolean = false;
  fedexPriorityAlertPlus: boolean = false;
  freightClass: string = '';
  futureDayShipmentFlag: boolean = false;
  indicaType: string = '';
  intlQty: number = 0;
  intlUnitUom: string = '';
  intlUnitValue: number = 0;
  intlUnitWeight: number = 0;
  labelCount: number = 0;
  largePackageFlag: boolean = false;
  lpnnumber: string = '';
  lpnWeight: number = 0;
  nonPalletCount: number = 0;
  overSize: string = '';
  packageBaseCharges: number = 0;
  packageDeclaredValue: number = 0;
  packageDescription: string = '';
  packageDiscountCharges: number = 0;
  packageHeight: number = 0;
  packageLength: number = 0;
  packageWidth: number = 0;
  packageShipmentCost: number = 0;
  packagesCount: number = 0;
  packaging: string = '';
  packagingInstructions: string = '';
  packagingType: string = '';
  palletCount: number = 0;
  palletnumber: string = '';
  pieces: number = 0;
  pkgDiscountNetCharges: number = 0;
  pkgListNetCharges: number = 0;
  pkgnumber: number = 0;
  signatureName: string = '';
  signatureOption: string = '';
  stampsTaxId: string = '';
  starTrackEodFlag: string = '';
  starTrackShipmentId: string = '';
  trackingNumber: string = '';
  trailernumber: string = '';
  transitTime: string = '';
  dimUom: string = '';
  upsLabelDeliveryMethod: number = 0;
  codInfo: CodInfo = new CodInfo();
  holdAtLocInfo: HoldAtLocInfo = new HoldAtLocInfo();
  returnShipmentInfo: ReturnShipmentInfo = new ReturnShipmentInfo();
  uspsPkgInfo: UspsPkgInfo = new UspsPkgInfo();
  ltlPkgInfo: LtlPkgInfo = new LtlPkgInfo();
  hazmatInfo: HazmatInfo = new HazmatInfo();
  pkgChargesInfo: ShipmentChargesInfo = new ShipmentChargesInfo();
}
