import { Lot } from "./lot.model";
import { Serial } from "./serial.model";
import { ShipmentItemControlsInfo } from "./shipment-item-controls-info";

export class ShipmentLinesInfo {
  clientId: number = 0;
  shipmentLineId: number = 0;
  shipmentId: number = 0;
  deliveryId: string = '';
  orderHeaderId: string = '';
  ordernumber: string = '';
  orderLineId: string = '';
  sourceLinenumber: string = '';
  lineNumber: number = 0;
  inventoryItemId: number = 0;
  itemnumber: string = '';
  itemDescription: string = '';
  unitWeight: number = 0;
  weight: number = 0;
  weightUom: string = '';
  orderedQuantity: number = 0;
  mappableQuantity: number = 0;
  shippedQuantity: number = 0;
  mappedQuantity: number = 0;
  quantityUom: number = 0;
  itemSellingPrice: number = 0;
  amountExtendedPrice: number = 0;
  unitPrice: number = 0;
  scheduledShipDate: string = '';
  serialControlCode: number = 0;
  transactionId: number = 0;
  invOrgId: string = '';
  orgId: string = '';
  revision: string = '';
  lotControlCode: number = 0;
  locatorName: string = '';
  locatorControlCode: number = 0;
  lotnumber: string = '';
  subinventory: string = '';
  hazardClassId: number = 0;
  lineStatus: string = '';
  itemClass: string = '';
  itemLength: number = 0;
  itemWidth: number = 0;
  itemHeight: number = 0;
  itemWeight: number = 0;
  itemDimensionsUnit: string = '';
  deliveryDetailId: string = '';
  shipmentItemControlsInfo: ShipmentItemControlsInfo [] = [];
}
