import { EmailNotificationInfo } from './email-notification-info';
import { FedExDirectDistInfo } from './fed-ex-direct-dist-info';
import { FxfrInfo } from './fxfr-info';
import { ShipExecLabelInfo } from './ship-exec-label-info';
import { StarTrackInfo } from './star-track-info';
import { TntInfo } from './tnt-info';
import { WorldEaseInfo } from './world-ease-info';

export class ShipmentCarrierDetails {
  carrierId!: number;
  clientId!: number;
  orgId!: string;
  invOrgId!: string;
  carrierCode!: number;
  carrierName!: string;
  carrierUrl!: string;
  carrierMode!: string;
  enabledFlag!: boolean;
  labelStockOrientation!: string;
  docTabLocation!: string;
  userName!: string;
  password!: string;
  labelFormat!: string;
  domain!: string;
  intlLabelFormat!: string;
  eodDocPrinterSymbol!: string;
  eodLabelFormat!: string;
  eodDocStockLabel!: string;
  eodDocPort!: string;
  hubId!: string;
  bolLabelFormat!: string;
  op900LabelFormat!: string;
  intlDocSubType!: string;
  dhlRegionCode!: string;
  docStockSymbol!: string;
  docModelSymbol!: string;
  erpCarrierScacCode!: string;
  erpCarrierName!: string;
  erpCarrierCode!: string;
  defaultSignatureOption!: string;
  genericLabelWithoutRateFlag!: boolean;
  stampsPaperSize!: string;
  intlLabelOrientation!: string;
  nonDelOption!: string;
  uspsPriceOption!: string;
  uspsReceiptOptions!: string;
  holdForManifest!: string;
  documentPort!: string;
  companyId!: string;
  cn22LabelFormat!: string;
  cn22FormLabelSize!: string;
  siteId!: string;
  dhlLogoFlag!: boolean;
  dhlLogoImage!: Uint8Array;
  generateSLI!: boolean;
  customCIDocument!: string;
  defaultRtnShipMethod!: string;
  generateGenericLabel!: boolean;
  generateSed!: boolean;
  apiKey!: string;
  labelModelSymbol!: string;
  labelStockSymbol!: string;
  labelPort!: string;
  emailNotificationInfo!: EmailNotificationInfo;
  fxfrInfo!: FxfrInfo;
  starTrackInfo!: StarTrackInfo;
  tntInfo!: TntInfo;
  shipExecLabelInfo!: ShipExecLabelInfo;
  worldEaseInfo!: WorldEaseInfo;
  dhlAPIKey!: string;
  profileName!: string;
  fedexDirectDistInfo!: FedExDirectDistInfo;
}
